-- ============================================================
-- Migration 003: Clinical Knowledge Base
-- Creates 3 new tables for the 6-persona intelligence engine:
--   1. clinical_knowledge_base - Pre-computed clinical analysis documents
--   2. hypothesis_evidence - Structured evidence for deterministic scoring
--   3. data_validation_flags - Flagged data entries needing user review
-- Uses IF NOT EXISTS to be safe against re-runs.
-- Does NOT modify or delete any existing tables.
-- ============================================================

-- 1. clinical_knowledge_base - Pre-computed clinical analysis documents
--    from the 6-persona intelligence engine. Each document represents
--    one persona's analysis output for a given date range or topic.
CREATE TABLE IF NOT EXISTS clinical_knowledge_base (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id VARCHAR(100) UNIQUE NOT NULL,
  document_type VARCHAR(30) NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  version INTEGER DEFAULT 1,
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  generated_by VARCHAR(50),
  metadata JSONB DEFAULT '{}',
  covers_date_start DATE,
  covers_date_end DATE,
  token_count INTEGER,
  is_stale BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_clinical_kb_document_id
  ON clinical_knowledge_base (document_id);

CREATE INDEX IF NOT EXISTS idx_clinical_kb_document_type
  ON clinical_knowledge_base (document_type);

CREATE INDEX IF NOT EXISTS idx_clinical_kb_stale
  ON clinical_knowledge_base (is_stale) WHERE is_stale = TRUE;

CREATE INDEX IF NOT EXISTS idx_clinical_kb_generated_at
  ON clinical_knowledge_base (generated_at DESC);

COMMENT ON TABLE clinical_knowledge_base IS
  'Pre-computed clinical analysis documents generated by the 6-persona intelligence engine. '
  'Each row is a versioned document (e.g. GI analysis, cardio summary) covering a specific date range.';

-- 2. hypothesis_evidence - Structured evidence items for deterministic
--    hypothesis scoring. Each row links a finding from a source table
--    to a hypothesis, with weights and correction flags.
CREATE TABLE IF NOT EXISTS hypothesis_evidence (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  hypothesis_id VARCHAR(100) NOT NULL,
  finding TEXT NOT NULL,
  source_table VARCHAR(50) NOT NULL,
  source_date DATE,
  source_reliability REAL NOT NULL DEFAULT 1.0,
  supports BOOLEAN NOT NULL,
  clinical_weight REAL NOT NULL DEFAULT 1.0,
  fdr_corrected BOOLEAN DEFAULT FALSE,
  meets_criteria_rule BOOLEAN DEFAULT FALSE,
  is_anchored BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_hypothesis_evidence_hypothesis_id
  ON hypothesis_evidence (hypothesis_id);

CREATE INDEX IF NOT EXISTS idx_hypothesis_evidence_source
  ON hypothesis_evidence (source_table, source_date);

COMMENT ON TABLE hypothesis_evidence IS
  'Structured evidence items for deterministic hypothesis scoring. '
  'Each row links a clinical finding to a hypothesis with reliability weights and FDR correction flags.';

-- 3. data_validation_flags - Flagged data entries that need user review.
--    Covers anomalies, range violations, and suspicious values detected
--    during data ingestion or periodic validation sweeps.
CREATE TABLE IF NOT EXISTS data_validation_flags (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_table VARCHAR(50) NOT NULL,
  source_id UUID,
  source_date DATE,
  flag_type VARCHAR(30) NOT NULL,
  field_name VARCHAR(50),
  original_value TEXT,
  expected_range TEXT,
  severity VARCHAR(20) DEFAULT 'warning',
  resolved BOOLEAN DEFAULT FALSE,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_data_validation_flags_unresolved
  ON data_validation_flags (resolved) WHERE resolved = FALSE;

CREATE INDEX IF NOT EXISTS idx_data_validation_flags_source
  ON data_validation_flags (source_table, source_date);

COMMENT ON TABLE data_validation_flags IS
  'Flagged data entries needing user review: anomalies, range violations, and suspicious values '
  'detected during ingestion or periodic validation sweeps.';
