-- Migration 039: cycle_messages table.
--
-- Adds the smart-logging Messages inbox surface used by /v2/cycle/messages.
-- Each row is one phase-aware reminder generated by
-- src/lib/cycle/messages.ts and stored idempotently per
-- (user_id, dedupe_key).
--
-- Idempotent: every CREATE clause uses IF NOT EXISTS or DO blocks.
-- ZERO data loss: pure additive, no DROPs.

CREATE TABLE IF NOT EXISTS cycle_messages (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  kind         text NOT NULL,
  title        text NOT NULL,
  body         text NOT NULL,
  dedupe_key   text NOT NULL,
  dismissed    boolean NOT NULL DEFAULT false,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cycle_messages_kind_check CHECK (
    kind IN (
      'morning_temp_reminder',
      'fertile_window_approaching',
      'period_start_predicted',
      'cycle_insight_ready'
    )
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS cycle_messages_user_dedupe_idx
  ON cycle_messages (user_id, dedupe_key);

CREATE INDEX IF NOT EXISTS cycle_messages_user_created_idx
  ON cycle_messages (user_id, created_at DESC);

ALTER TABLE cycle_messages ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'cycle_messages'
      AND policyname = 'cycle_messages_owner_select'
  ) THEN
    CREATE POLICY cycle_messages_owner_select
      ON cycle_messages FOR SELECT TO authenticated
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'cycle_messages'
      AND policyname = 'cycle_messages_owner_update'
  ) THEN
    CREATE POLICY cycle_messages_owner_update
      ON cycle_messages FOR UPDATE TO authenticated
      USING (auth.uid() = user_id);
  END IF;
END$$;

COMMENT ON TABLE cycle_messages IS
  'Phase-aware reminder cards surfaced on /v2/cycle/messages. Generated by src/lib/cycle/messages.ts and persisted idempotently per (user_id, dedupe_key).';
