/**
 * Schema for AI-extracted candidate stamps from a free-form note.
 *
 * The composer-save path runs Claude over the note body and gets
 * back a list of candidate entities. Each one is stored on the
 * notes.extractions JSONB column and surfaced as a tappable chip.
 * The user explicitly confirms each chip; nothing is silently
 * stamped into structured tables.
 *
 * The structured table writes (med_doses, pain_points, etc.) only
 * happen at the moment the user taps a chip. Until then the
 * extractions are just suggestions on the note row.
 */

export type ExtractionKind =
  | 'med_dose'
  | 'pain'
  | 'headache_attack'
  | 'symptom'

export interface BaseExtraction {
  /** Stable id within the note (so the apply route can reference it). */
  id: string
  kind: ExtractionKind
  /**
   * Short human label rendered on the chip ("Tylenol at 2:15 pm",
   * "Headache 7/10"). Generated by the model; rendered verbatim.
   */
  chip_label: string
  /** Confidence band: low / medium / high (model self-rates). */
  confidence: 'low' | 'medium' | 'high'
  /**
   * Optional verbatim slice from the note body that triggered this
   * suggestion. Useful for the user to see "what made the AI think
   * this" if they tap-and-hold the chip. Always a substring of the
   * original note body (no paraphrasing).
   */
  evidence_quote?: string
}

export interface MedDoseExtraction extends BaseExtraction {
  kind: 'med_dose'
  /** Slug from the user's med list (matches MedsConfig.slug). */
  med_slug: string
  med_name: string
  scheduled_or_prn: 'scheduled' | 'prn'
  slot?: 'morning' | 'midday' | 'night' | null
  /** ISO timestamp the dose was taken. */
  taken_at_iso: string
  dose_text?: string | null
}

export interface PainExtraction extends BaseExtraction {
  kind: 'pain'
  /** 0-10 NRS rating. */
  intensity: number
  /** Free-form region label ("head", "lower back", "left side"). */
  body_region?: string | null
  pain_quality?: string | null
  /** ISO timestamp the user is rating about (start of episode). */
  noted_at_iso: string
}

export interface HeadacheAttackExtraction extends BaseExtraction {
  kind: 'headache_attack'
  /** ISO start time of the attack. */
  started_at_iso: string
  intensity?: number | null
  /** Free-form side label: 'left' | 'right' | 'bilateral' | string. */
  side?: string | null
  /** Free-form aura description. */
  aura?: string | null
  /** Free-form trigger guess. */
  trigger?: string | null
}

export interface SymptomExtraction extends BaseExtraction {
  kind: 'symptom'
  /** Short symptom label. ("nausea", "tinnitus", "brain fog"). */
  label: string
  intensity?: number | null
  noted_at_iso: string
}

export type Extraction =
  | MedDoseExtraction
  | PainExtraction
  | HeadacheAttackExtraction
  | SymptomExtraction
